#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npm run type-check -w @shibui-ui/ui

cd packages/shibui-ui && npx lint-staged && npx stylelint --config .config/.stylelintrc.json --fix "src/**/*.css"